### ISSUE TITLE
Wrath - Experimental mode?

### ISSUE THREAD

**Issue by XyzKangUI** [Verubato/frame-sort#1]
I don't know if its coincidence or not, but yesterday I've made your retail version work with wrath. Today I see a wrath release, but unfortunately it does not have the great and working experimental mode. Any plans to add it to the wrath release?

Here is the ported version:
[FrameSort-WOTLKC.zip](https://github.com/Verubato/frame-sort/files/10774485/FrameSort-WOTLKC.zip)

**Comment by Verubato** [comment]
Hey there, I received a private message today from someone on CurseForge asking for Wotlk support so I added it in. Guess it's just a lucky coincidence!

Are the taint/ui issues happening in Wrath as well? I don't play Wrath so I didn't do much testing.

Sure, I'll look into porting over the experimental mode to Wrath as well.

**Comment by XyzKangUI** [comment]
The current implemented method (non experimental) will cause taints indeed, hence your addon caught my attention when you implemented the experimental feature. So far it seems to be all good while using it.

**Comment by Verubato** [comment]
Oh is the experimental mode already working in Wrath? If so I'll just merge in your changes right away.

**Comment by XyzKangUI** [comment]
> Oh is the experimental mode already working in Wrath? If so I'll just merge in your changes right away.

Eh yes it seems to work fine, didnt change anything to the LayoutRaid function afaik.

**Comment by Verubato** [comment]
Ok awesome. I've just published a new version with experimental mode added to Wrath.
Heading to bed now so I can check any further feedback tomorrow. Hope it all works!
