### ISSUE TITLE
Frames resort when mind control is cast

### ISSUE THREAD

**Issue by clicketz** [Verubato/frame-sort#11]
Might be related to #10 but any time I, or anybody on my team, lands a successful mind control the frames resort (and to the wrong location). Happens every time.

**Comment by Verubato** [comment]
Oh wow interesting, thanks for letting me know.
I'll test/fix this in conjunction with #10.

**Comment by Verubato** [comment]
Can confirm issue still exists with latest changes/fixes from #10.

Appears to only happen when "Display Pets" is enabled for raid frames. If I disable this option the bug doesn't occur.

**Comment by SweepyBoop** [comment]
Hmm interesting, does "Display Pets" even work now? I still don't see any pet frames with it enabled 😅

**Comment by clicketz** [comment]
No, "Display Pets" does nothing but break addons apparently. Pets are still bugged/missing in 10.1. Good to find the issue now for when blizzard *hopefully* fixes pet frames in the near future.

**Comment by Verubato** [comment]
I've just released 5.0.0 that might fix this issue. More details in #10.

**Comment by Verubato** [comment]
Seems to be resolved now with the fixes from #11. 

I'll wait a few days for any other news/feedback from the community and then close this off.

**Comment by clicketz** [comment]
Q'd all day today with no issues. Seems to be fixed.

**Comment by Verubato** [comment]
Seems to be fixed now, closing issue.
