### ISSUE TITLE
PartyPets Fix issue with experimental mode

### ISSUE THREAD

**Issue by burnep** [Verubato/frame-sort#2]
I'm not sure which addon (framesort or partypets) is causing this, but this only happens for FrameSort experimental mode.

PartyPets Fix addon (https://www.curseforge.com/wow/addons/partypets-fix) adds a clickable frame for pets to fix the DF bug, but using framesort the frames are no longer recognized and show like this:

![pets](https://user-images.githubusercontent.com/40314230/219993310-369930ec-1d98-46a2-b3d6-2f3774e3e048.png)

Will also post to that addon's github, but since it's not a problem for SortGroup *OR* Frame Sort non-experimental, thought you should know.

Cheers

**Comment by Verubato** [comment]
Thanks for the detailed bug report with screenshots.
Looking into the issue.

**Comment by Verubato** [comment]
I've added a comment to the PPF issue https://github.com/cleanlock/PartyPets-Fix/issues/4 with some suggestions on how we could fix this.

**Comment by Verubato** [comment]
I'll close this issue off FrameSort as the fix is going to be made to the PartyPetsFix addon.

https://github.com/cleanlock/PartyPets-Fix/issues/4
