### ISSUE TITLE
Raid frame issue with experimental mode

### ISSUE THREAD

**Issue by jovaye** [Verubato/frame-sort#3]
It doesn't seem to happen consistently, but, sometimes when I join a 10 man raid group with experimental mode active I either am only able to see 1 member from each of group 1 or 2, or, I see everybody but only the top of member of group 1 and 2 are interactable. I'm not able to click, or see hp changes/buffs/debuffs on anyone else in the raid.

I tried to enable/reenable raid frames, shut the game off and back on, move people in and out of groups. I tried to have experimental mode enabled, but, disable all sorting for raid groups all to no avail. It seems to only happen about 70-80% of the time, but once it does happen I'm only able to fix it by disabling experimental mode and reloading.

**Comment by Verubato** [comment]
Thanks for the bug report, and I think I get what you mean.

Would you happen to have a screenshot of what's happening?

I'll look into the issue and keep you posted!

**Comment by Verubato** [comment]
I've just release a new version 3.0.0 with some improvements to Experimental mode that may resolve this.

Could you please give it a try and see how it goes?

**Comment by jovaye** [comment]
Just noticed my last reply didn't post! I wasn't able to determine any patterns to it previously. I didn't grab any screenshots either unfortunately, but I've updated to 3.0 and should be que'ing rbgs later I'll report back if it happens anymore, with screenshots if it does!

Thank you :)

**Comment by Verubato** [comment]
Don't suppose you've had a chance to test it out yet?

**Comment by jovaye** [comment]
I haven't the issue come up the couple time's Ive been in 10 man groups, but I haven't played much the last few days. If it does happen again I'll definitely respond with screenshots. Would there be any thing else helpful I can provide if it does happen?

Also, is there a way to sort so it would it go

Player
Party 2
Party 1

I use Mousewheel up / middle mouse / mousewheel down for targeting but I want to be able to use MWD for Party 1 so when I'm queing 2s I just use MWU/MWD

**Comment by Verubato** [comment]
Ok cool, I've done some testing myself in BGs and I think this issue has been resolved now so I'll close this bug ticket off.
Feel free to re-open though if the issue occurs again.

Regarding the reverse/descending party order,  currently there isn't a way to do this. 
I'll open a new issue as a feature request #5 and work on implementing a solution.
