### ISSUE TITLE
Feature request: reverse/descending ordering

### ISSUE THREAD

**Issue by Verubato** [Verubato/frame-sort#5]
As requested by Jovaye in #3

Currently sorting by group orders party members in ascending order, i.e.

party1
party2
party3

There may be some use cases where people would prefer the reverse order, i.e.

party3
party2
party1

Request implementing a reverse/descending ordering feature.

**Comment by jovaye** [comment]
heya, just wondering if this might be something that gets implemented soon?  I've been swapping the keybinds manually whether I'm queueing 2s or 3s but considering a shot at making a addon that will change the binds automatically - nonsensical if you might implement this soon though. Thank you for all the work you've done though - haven't ran into any issues recently.

**Comment by Verubato** [comment]
Hey thanks for the reminder.
I've just released 4.1.0 with this feature added in now.
Enjoy :)

**Comment by Verubato** [comment]
Test
