### ISSUE TITLE
Feature request: Hide player frame

### ISSUE THREAD

**Issue by XyzKangUI** [Verubato/frame-sort#9]
Hi there, me again.

I think that it would be nice to have as a feature to hide the frame of the player unit. 

I achieved that by doing the following:

```
            if UnitIsUnit(sourceUnit, "player") then
                source.Frame:SetPoint("TOP", UIParent, "BOTTOMLEFT", 10000, 10000)
            else
                source.Frame:SetPoint(unpack(point))
            end
```

Although since the implementation of spacing it gets messy.

**Comment by Verubato** [comment]
Sounds like a good feature to add!

I'll work on adding this in.

**Comment by Verubato** [comment]
Hey @XyzKangUI, I've just pushed a first attempt at this. If you happen to be around and able to give it a quick test that'd be amazing.

**Comment by XyzKangUI** [comment]
@Verubato I don't get online notifications, but I felt you pinging me mentally. Will test it out right away.

**Comment by XyzKangUI** [comment]
The new feature seems to work great, great job. I've only tested it out quickly in one battleground. Although, I noticed there is 1 sorting issue, which might have pre-existed due to pet frames or.. ? 

![image](https://user-images.githubusercontent.com/94811434/236220863-bcdb932d-d373-4045-bb7c-0004abe440a7.png)

**Comment by Verubato** [comment]
Ah yeah I had this today as well in a BG. 
I think it's a spacing feature issue when people join and leave the group.
Will add it to my TODO list to fix!

**Comment by XyzKangUI** [comment]
There is a rare bug in 2v2 arena where it the partner. After swapping from "Hidden" to any of the other 3 it will show "player" but not the partner.

**Comment by Verubato** [comment]
Had a quick look at this today and seems to be related to the spacing module.

The frames become overlapped and other weirdness when switching to/from "Hidden". When disabling spacing it seems to work fine.

Not sure if it's the same bug as before due to recent fixes/changes, but something I need to fix nonetheless.

**Comment by Verubato** [comment]
Release 5.0.3 has some fixes in this area that might help, haven't tested it yet though.

**Comment by XyzKangUI** [comment]
![image](https://github.com/Verubato/frame-sort/assets/94811434/092431de-258b-49df-b569-3bacbc8b73f9)
Text position could be a bit better, going to try out if any fragmentation happends.

**Comment by Verubato** [comment]
Oh weird the text overlap is happening in classic and wotlk but not retail or the wotlk ptr. Thanks for showing me otherwise I wouldn't have known.

**Comment by Verubato** [comment]
Closing as fixed.
